export const books = [
  {
    id: '1',
    name: 'The Catcher in the Rye',
    price: 15.99,
    category: 'Fiction',
    description: 'A classic novel by J.D. Salinger.',
  },
  {
    id: '2',
    name: 'To Kill a Mockingbird',
    price: 12.99,
    category: 'Fiction',
    description: 'Harper Lee\'s Pulitzer Prize-winning novel.',
  },
  {
    id: '3',
    name: '1984',
    price: 18.99,
    category: 'Dystopian',
    description: 'George Orwell\'s influential dystopian novel.',
  },
  {
    id: '4',
    name: 'The Great Gatsby',
    price: 14.99,
    category: 'Fiction',
    description: 'F. Scott Fitzgerald\'s masterpiece of the Jazz Age.',
  },
  {
    id: '5',
    name: 'Harry Potter and the Sorcerer\'s Stone',
    price: 22.99,
    category: 'Fantasy',
    description: 'J.K. Rowling\'s magical debut in the wizarding world.',
  },
  {
    id: '6',
    name: 'The Hobbit',
    price: 17.99,
    category: 'Fantasy',
    description: 'J.R.R. Tolkien\'s classic adventure novel.',
  },
  {
    id: '7',
    name: 'The Hunger Games',
    price: 16.99,
    category: 'Dystopian',
    description: 'Suzanne Collins\' gripping tale of survival.',
  },
  {
    id: '8',
    name: 'Pride and Prejudice',
    price: 13.99,
    category: 'Romance',
    description: 'Jane Austen\'s timeless romantic novel.',
  },
  {
    id: '9',
    name: 'The Alchemist',
    price: 20.99,
    category: 'Philosophical Fiction',
    description: 'Paulo Coelho\'s bestselling philosophical novel.',
  },
  {
    id: '10',
    name: 'The Lord of the Rings',
    price: 25.99,
    category: 'Fantasy',
    description: 'J.R.R. Tolkien\'s epic fantasy trilogy.',
  },
];
